name: CI

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
           - 'swift:5.5-focal'
    container: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test --sanitize=thread
  macos:
    runs-on: macos-11
    strategy:
      matrix:
        xcode:
          - '13.1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: swift test --sanitize=thread