name: Documentation

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docs
        run: xcodebuild docbuild -scheme "Validations" -destination 'platform=macOS,arch=x86_64' -derivedDataPath ../DerivedData
      - name: Publish docs
      - run: |
          git fetch --no-tags --prune --no-recurse-submodules origin docc
          git switch docc
          mv -f ../DerivedData/Build/Products/Debug/Validations.doccarchive docs.doccarchive
          rm -rf ../DerivedData
          git add docs.doccarchive
          git commit -m "Update documentation"
          git push
          git switch - || git checkout -
            
